version: '3.4'

services:

  agentdb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  agent.web:
    image: ${DOCKER_REGISTRY-}agentweb
    build:
      context: .
      dockerfile: Agent.Web/Dockerfile
